### ISSUE TITLE
Error on "Next Turn" in certain systems

### ISSUE THREAD

**Issue by MNielson** [EndlessFractal/yourTurn#1]
When using YourTurn with Exalted Essence (and probably other systems that use initiative in the same way), an error occurs when Next Turn is clicked.

![image](https://github.com/EndlessFractal/yourTurn/assets/23503856/89d2f27b-74bb-4cd6-b436-3e7b9f67dcd9)

Exalted Essence uses "popcorn initiative". This means initiative is only used on the very first turn to determins who goes first. After that initiative passes back and forth freely, without regard for the initiative value.
Exalted Essence, as a system implemented on Foundry, does not have an active character when the next turn button is clicked. This (presumably) causes an error as listed above.

**Comment by EndlessFractal** [comment]
Can you please supply the error in text?

Cheers!

**Comment by MNielson** [comment]
foundry.js:753 TypeError: Error thrown in hooked function '' for hook 'updateCombat'. Cannot read properties of undefined (reading 'actor')
[Detected 1 package: your-turn]
    at TurnSubscriber._onUpdateCombat (main.js:54:39)
    at Object.fn (main.js:20:26)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13709:13)
    at foundry.js:13682:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13682:33)
onError @ foundry.js:753
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
#call @ foundry.js:734
callAll @ foundry.js:687
callback @ foundry.js:13709
(anonymous) @ foundry.js:13682
#handleUpdateDocuments @ foundry.js:13682
await in #handleUpdateDocuments (async)
_updateDocuments @ foundry.js:13429
await in _updateDocuments (async)
update @ commons.js:8578
await in update (async)
updateDocuments @ commons.js:7902
update @ commons.js:7999
nextRound @ exaltedessence.js:384
await in nextRound (async)
_onCombatControl @ foundry.js:85601
(anonymous) @ foundry.js:85538
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
main.js:105 <img id=​"yourTurnImg4" class=​"yourTurnImg" src=​"icons/​svg/​mystery-man.svg">​
main.js:189 <div class="yourTurnSubheading last">Next Up:  <img class="yourTurnImg yourTurnSubheading" src="icons/svg/mystery-man.svg"></img>test</div>
foundry.js:733 Foundry VTT | Error thrown in hooked function '' for hook 'updateCombat'
#call @ foundry.js:733
callAll @ foundry.js:687
callback @ foundry.js:13709
(anonymous) @ foundry.js:13682
#handleUpdateDocuments @ foundry.js:13682
await in #handleUpdateDocuments (async)
_updateDocuments @ foundry.js:13429
await in _updateDocuments (async)
update @ commons.js:8578
await in update (async)
updateDocuments @ commons.js:7902
update @ commons.js:7999
nextRound @ exaltedessence.js:384
await in nextRound (async)
_onCombatControl @ foundry.js:85601
(anonymous) @ foundry.js:85538
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
foundry.js:753 TypeError: Error thrown in hooked function '' for hook 'updateCombat'. Cannot read properties of undefined (reading 'actor')
[Detected 1 package: your-turn]
    at TurnSubscriber._onUpdateCombat (main.js:54:39)
    at Object.fn (main.js:20:26)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13709:13)
    at foundry.js:13682:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry.js:13682:33)
onError @ foundry.js:753
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁Hooks.onError#lib-wrapper @ listeners.js:138
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
#call @ foundry.js:734
callAll @ foundry.js:687
callback @ foundry.js:13709
(anonymous) @ foundry.js:13682
#handleUpdateDocuments @ foundry.js:13682
await in #handleUpdateDocuments (async)
_updateDocuments @ foundry.js:13429
await in _updateDocuments (async)
update @ commons.js:8578
await in update (async)
updateDocuments @ commons.js:7902
update @ commons.js:7999
nextRound @ exaltedessence.js:384
await in nextRound (async)
_onCombatControl @ foundry.js:85601
(anonymous) @ foundry.js:85538
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by EndlessFractal** [comment]
I've tried to address this in the dev branch. Please copy and replace the script file inside this directory:

Windows: %localappdata%\FoundryVTT\Data\modules\your-turn\scripts

Updated file: https://raw.githubusercontent.com/EndlessFractal/yourTurn/dev/scripts/main.js

Please check if the issue still occurs.

**Comment by MNielson** [comment]
The error is indeed gone, however, now NO turns get announced in Exalted:Essence. No error or warnings.

**Comment by EndlessFractal** [comment]
This is probably going to take me a long time to solve as I'm not familiar with that game system. I mainly play D&D 5e and Cyberpunk RED. I'll have to look into how it works and how to best implement it. I'm marking as help wanted.

**Comment by EndlessFractal** [comment]
I'm taking another crack at this. I'm doing some basic tests on my end, but I'll need your help to see if everything is working correctly.

I'll post an updated alpha tomorrow!

**Comment by EndlessFractal** [comment]
Fixed with https://github.com/EndlessFractal/yourTurn/releases/tag/1.4.4!
